ObjectDetector:
  seed: 42
  data:
    path: 'Data/'
    test_percent: 0.2
  train:
    epochs: 100
    batch_size: 8
    # save_path: /content/gdrive/MyDrive/NeuraSens/data/Artifacts/saved_model/ #colab
    # tensorboard_path: /content/gdrive/MyDrive/NeuraSens/data/Artifacts/tensor_board/ #colab
  model:
    path: "Model/voc.weights.h5"
  lr:
    initial_lr: 0.001
    