#anchors
VARIANCES = [0.1, 0.1, 0.2, 0.2]
IOU_THRESHOLD = 0.5
CONFIDENCE = 0.5
POST_IOU_THRESHOLD = 0.5
TOP_K_CLASSES = 100

#dataset
DATASET_PATH = "Data/"
TEST_PERCENT = 0.2

#model
MODEL_PATH = "Model/model.weights.h5"
IMG_SIZE = 300
FAST_WIDTH = 0.5
SLOW_WIDTH = 1.0

#train
LOGS_PATH = "Logs/"
SEED = 42
EPOCHS = 30
BATCH_SIZE = 8
AUGMENTATION = True

#lr
LR = 0.0001
MIN_LR = None